#define WIFI_SSID "<REPLACE_WITH_YOUR_WIFI_SSID>"
#define WIFI_PASS "<REPLACE_WITH_YOUR_WIFI_PASSWORD>"
#define WHATSAPP_ACCESS_TOKEN "<REPLACE_WITH_WHATSAPP_ACCESS_TOKEN>"
#define TARGET_PHONE_NUMBER "<REPLACAE_WITH_TARGET_WHATSAPP_NUMBER>"
